import Link from 'next/link';
import { ArrowUpRight, HeartHandshake, Languages, Lightbulb, Users, type LucideIcon } from 'lucide-react';
import { TeamSection } from '../../components/team-section';

const values: { icon: LucideIcon; title: string; text: string }[] = [{ icon: HeartHandshake, title: 'Belonging', text: 'A warm school culture where each learner is seen.' }, { icon: Lightbulb, title: 'Curiosity', text: 'Learning that turns questions into possibilities.' }, { icon: Languages, title: 'Perspective', text: 'Chinese and French for a wider world.' }, { icon: Users, title: 'Partnership', text: 'Families and teachers working together.' }];

export default function About() { return <main>
  <PageIntro label="Our school" title={<>A foundation for <span>great futures.</span></>} text="Fordsbed Trust School is a caring, ambitious learning community where every learner is known, challenged and encouraged to grow."/>
  <section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow mb-4">School background</p><h2 className="font-display text-4xl leading-tight text-navy">A school rooted in <span className="text-gold">purpose.</span></h2><p className="mt-6 text-base leading-8 text-slate-600">Fordsbed Trust School is a privately-owned business. It is situated on the outskirts of Lusaka, the capital city, about 16 kilometers away, along Mumbwa Road near Kalundu.</p><p className="mt-5 text-base leading-8 text-slate-600">It is a co-educational institution catering to students from daycare to Grade Twelve.</p><div className="mt-8 rounded-2xl bg-navy p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-400">Our guiding values</p><p className="mt-4 font-display text-2xl leading-snug">RIDE</p><p className="mt-2 text-sm leading-7 text-white/70">Respect, Integrity, Diversity, &amp; Excellence.</p></div></div><div className="rounded-3xl bg-cream p-8 sm:p-10"><p className="eyebrow mb-5">Our direction</p><div className="border-b border-slate-200 pb-8"><h2 className="font-display text-3xl text-navy">Our Mission</h2><p className="mt-4 text-base leading-8 text-slate-600">To cultivate an inclusive and empowering learning community that fosters academic excellence, personal growth, and social responsibility.</p></div><div className="pt-8"><h2 className="font-display text-3xl text-navy">Our Vision</h2><p className="mt-4 text-base leading-8 text-slate-600">To deliver flexible and distinctive care services that exceed the expectations of our clients.</p></div></div></section>
  <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow mb-4">Our promise</p><h2 className="font-display text-4xl leading-tight text-navy">Education with a little more <span className="text-gold">heart.</span></h2></div><div className="space-y-5 text-base leading-8 text-slate-600"><p>We believe the best education gives children both roots and wings: a secure sense of self, and the confidence to look outward with curiosity.</p><p>Our CBC learning approach blends strong academic foundations with practical skills, creative expression, languages and the everyday habits of character that help learners thrive.</p></div></section>
  <section className="bg-cream py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(({ icon: Icon, title, text })=><div key={title} className="rounded-2xl bg-white p-7"><Icon className="mb-12 text-gold" size={28}/><h3 className="font-display text-2xl text-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></div></section>
  <TeamSection />
  <section className="mx-auto max-w-7xl px-5 py-24 text-center lg:px-8"><p className="eyebrow mb-5">Come and see for yourself</p><h2 className="mx-auto max-w-2xl font-display text-4xl text-navy">The right school feels like <span className="text-gold">a beginning.</span></h2><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-navy px-6 py-4 text-sm font-bold text-white">Plan a visit <ArrowUpRight size={17}/></Link></section>
</main> }

function PageIntro({label,title,text}:{label:string;title:React.ReactNode;text:string}) { return <section className="about-hero bg-navy px-5 pb-20 pt-52 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow mb-6 text-amber-400">{label}</p><h1 className="max-w-3xl font-display text-5xl leading-tight sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-white/65">{text}</p></div></section> }
