'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Send } from 'lucide-react';

const schema = z.object({ name: z.string().min(2, 'Please enter your name'), grade: z.string().min(1, 'Please choose a grade'), phone: z.string().min(7, 'Please enter a valid phone number'), message: z.string().min(10, 'Please tell us a little more') });
type FormValues = z.infer<typeof schema>;
export function InquiryForm() { const [sent, setSent] = useState(false); const [sendError, setSendError] = useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema) }); const submit = async (data: FormValues) => { setSendError(''); const response = await fetch('/api/send-email', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'Contact inquiry', data }) }); if (!response.ok) { setSendError('We could not send your message. Please call 0779 809 913.'); return; } setSent(true); }; return sent ? <div className="rounded-2xl bg-emerald-50 p-8 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-full bg-emerald-600 text-white">✓</div><h3 className="font-display text-2xl text-navy">Thank you for reaching out.</h3><p className="mt-2 text-sm leading-6 text-slate-600">Our admissions team will be in touch shortly.</p></div> : <form onSubmit={handleSubmit(submit)} className="grid gap-5 sm:grid-cols-2"><Field label="Parent / guardian name" error={errors.name?.message}><input {...register('name')} placeholder="Your full name" /></Field><Field label="Grade interested in" error={errors.grade?.message}><select {...register('grade')} defaultValue=""><option value="" disabled>Select a grade</option><option>Crèche</option><option>Nursery</option><option>Grade 1–7</option><option>Form 1–4</option></select></Field><Field label="Parent phone number" error={errors.phone?.message}><input {...register('phone')} placeholder="0779 809 913" /></Field><Field label="Your message" error={errors.message?.message} wide><textarea {...register('message')} rows={4} placeholder="How can we help?" /></Field>{sendError && <p className="sm:col-span-2 text-sm text-red-600">{sendError}</p>}<button disabled={isSubmitting} className="inline-flex w-fit items-center gap-2 rounded-full bg-plum px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#682943] disabled:opacity-60">{isSubmitting ? 'Sending…' : 'Send inquiry'} <Send size={16}/></button></form> }
function Field({ label, error, children, wide }: { label: string; error?: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? 'sm:col-span-2' : ''}><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-500">{label}</span>{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label> }
