'use client';

import Link from 'next/link';
import { Menu, X, ArrowUpRight } from 'lucide-react';
import { usePathname } from 'next/navigation';
import { useState } from 'react';

const links = [['Home', '/'], ['About', '/about'], ['Admissions', '/admissions'], ['News & updates', '/news'], ['Contact', '/contact']];

export function SiteHeader() { const [open, setOpen] = useState(false); const pathname = usePathname(); const isActive = (href: string) => href === '/' ? pathname === '/' : pathname.startsWith(href); return <>
  <div className="bg-gold px-5 py-2 text-center text-[11px] font-bold uppercase tracking-[.18em] text-white">Enrollment ongoing for selected grades — call 0779 809 913</div>
  <header className="absolute left-0 right-0 top-8 z-30 border-b border-white/15 bg-navy/90 text-white backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3" onClick={() => setOpen(false)}><img src="/images/logo.png" alt="Fordsbed Trust School logo" className="h-11 w-11 rounded-full object-contain" /><span className="leading-none"><b className="block font-display text-xl font-bold tracking-tight">Fordsbed</b><small className="mt-1 block text-[9px] font-bold uppercase tracking-[.28em] text-white/65">Trust School</small></span></Link><nav className="hidden items-center gap-8 md:flex">{links.map(([label, href]) => <Link key={href} href={href} aria-current={isActive(href) ? 'page' : undefined} className={`relative py-2 text-sm font-semibold transition ${isActive(href) ? 'text-amber-400 after:absolute after:bottom-0 after:left-0 after:h-0.5 after:w-full after:bg-amber-400' : 'text-white/75 hover:text-gold'}`}>{label}</Link>)}<Link href="/admissions" className="group flex items-center gap-2 rounded-full bg-plum px-5 py-3 text-sm font-bold text-white transition hover:bg-[#682943]">Enroll now <ArrowUpRight size={16} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link></nav><button aria-label={open ? 'Close menu' : 'Open menu'} className="rounded-full border border-white/20 p-2 md:hidden" onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button></div>{open && <nav className="border-t border-white/10 bg-navy px-5 pb-6 pt-3 md:hidden">{links.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} aria-current={isActive(href) ? 'page' : undefined} className={`block border-b border-white/10 py-4 font-semibold ${isActive(href) ? 'text-amber-400' : 'text-white/90'}`}>{label}</Link>)}<Link href="/admissions" onClick={() => setOpen(false)} className="mt-5 block rounded-full bg-plum px-5 py-3 text-center font-bold">Enroll now</Link></nav>}</header>
</> }
